### ISSUE TITLE
Alive?

### ISSUE THREAD

**Issue by Semigradsky** [andrewbredow/Library-Detector-for-Chrome#66]
@andrewbredow  Is this project still alive? You need contributors?
This project is great. I would like him to develop.

**Comment by robertpataki** [comment]
+1 @Semigradsky I love this project but it seems long forgotten and abandoned :( If @andrewbredow is too busy I could offer to take ownership and help maintaining this awesome little tool.

**Comment by tatablack** [comment]
I wouldn't mind joining in. At the moment I'm running my own fork of the extension, and I think there's potential for more features.

**Comment by andrewbredow** [comment]
Hey everyone - thanks for getting in touch! I appreciate everyone's enthusiasm with this extension. As you've gathered, my time is a bit limited lately and I have not been able to keep this extension updated.

I'm happy to announce that @johnmichel will be taking over as development lead on the project. He's been active in since very early in development and is committed to keeping things moving along, and working with contributors to add new features!

I'm just about to transfer ownership to him, and I'll be excited to see how things progress!

**Comment by Semigradsky** [comment]
It's wonderful! :clap:
